App\Entity\Cliente:
  properties:
    nombre:
      - NotBlank: ~

    apellidos:
      - NotBlank: ~

    telefono:
      - NotBlank: ~
      - Length:
          max: 9
          maxMessage: 'El telefono no puede tener mas de 9 numeros'