# Ojo, no se ponen las variables que hacen referencia a relaciones
# Y no es obligatorio poner todas las variables

App\Entity\Direccion:
  properties:
    calle:
      - NotBlank: ~

    numero:
      - NotBlank: ~

    cod_postal:
      - NotBlank: ~